### ISSUE TITLE
Unit tests fail for recent build

### ISSUE THREAD

**Issue by ssable** [Trax-air/swagger-stub#10]
Running tox for the project, I get the same error with py33 and py35.
Seeing that travis has not been run for 2 years, it may be some dependency that was updated and broek the tests.

---------------------------- Captured stderr call -----------------------------
Exception in thread Thread-4:
Traceback (most recent call last):
  File "D:\Miniconda3\Lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "D:\Miniconda3\Lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "d:\swan\swagger-stub\.eggs\httpretty-0.8.14-py3.6.egg\httpretty\core.py", line 637, in fill_filekind
    headers
  File "D:\swan\swagger-stub\swagger_stub\swagger_stub.py", line 198, in get_data_from_request
    if swagger_parser.validate_request(path, action, data, query):
  File "d:\swan\swagger-stub\.eggs\swagger_parser-1.0.1-py3.6.egg\swagger_parser\swagger_parser.py", line 717, in validate_request
    is_ok, msg = self._validate_body_parameters(body, action_spec)
  File "d:\swan\swagger-stub\.eggs\swagger_parser-1.0.1-py3.6.egg\swagger_parser\swagger_parser.py", line 797, in _validate_body_parameters
    if not self.validate_definition(definition_name, body):
  File "d:\swan\swagger-stub\.eggs\swagger_parser-1.0.1-py3.6.egg\swagger_parser\swagger_parser.py", line 501, in validate_definition
    all_required_keys_present = all(req in dict_to_test.keys() for req in spec_def.get('required', {}))
  File "d:\swan\swagger-stub\.eggs\swagger_parser-1.0.1-py3.6.egg\swagger_parser\swagger_parser.py", line 501, in <genexpr>
    all_required_keys_present = all(req in dict_to_test.keys() for req in spec_def.get('required', {}))
AttributeError: 'NoneType' object has no attribute 'keys'

========================== 1 failed in 3.13 seconds ===========================

Thanks in advance

**Comment by cyprieng** [comment]
The build is now passing on master : [https://travis-ci.org/Trax-air/swagger-stub/builds/397901281](https://travis-ci.org/Trax-air/swagger-stub/builds/397901281) !
